apiVersion: skaffold/v2beta11
kind: Config

build:
  artifacts:
    - image: conditional-port-dock
      context: backend
    - image: port-dock-server
      context: server
deploy:
  kubectl:
    manifests:
      - ./k8s/*
profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: conditional-port-dock
          context: backend
          docker:
            buildArgs:
              ENV: development
          sync:
            manual:
              # Sync all the javascript files that are in the src folder
              # with the container src folder
              - src: "src/**/*.js"
                dest: .
        - image: port-dock-server
          context: server
          docker:
            buildArgs:
              ENV: development
          sync:
            manual:
              # Sync all the javascript files that are in the src folder
              # with the container src folder
              - src: "src/**/*.js"
                dest: .
